version: '3.9'

services:
  server:
    build: .
    ports:
      - "3001:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=prod # Set the NODE_ENV environment variable to 'prod'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data: